### ISSUE TITLE
No conflict-free timetable bug

### ISSUE THREAD

**Issue by navies** [morinted/schedule-generator#11]
Program fails to generate a timetable given two courses that have no conflicts.

To reproduce bug:
* Semester: Winter 2017
* Courses: [MAT2355](https://web30.uottawa.ca/v3/SITS/timetable/Course.aspx?code=CSI2120&session=20171), [CSI2120](https://web30.uottawa.ca/v3/SITS/timetable/Course.aspx?code=MAT2355&session=20171)

**Comment by davidschlachter** [comment]
This is just because the schedules on the server aren't/weren't up to date. I updated my server today and generated the schedule just fine.

![schedules](https://cloud.githubusercontent.com/assets/8271268/15726680/400a9f86-2820-11e6-8b39-11e75f4330cd.png)

**Comment by morinted** [comment]
Could you submit a PR with the updated csv's please?

**Comment by davidschlachter** [comment]
I’m posting the latest schedules [here](https://schlachter.ca/schedgen/) after each update (about once a week).

**Comment by davidschlachter** [comment]
Course databases are automatically updated on the server now.
