### ISSUE TITLE
Some courses failing to schedule

### ISSUE THREAD

**Issue by robotickoala** [morinted/schedule-generator#15]
It seems to have some issues working with the new system.

**Comment by davidschlachter** [comment]
I just opened it up and generated some schedules — please elaborate.

**Comment by robotickoala** [comment]
I've had some other people mention they cannot generate courses as well so i can't verify there exact methods but I opened the latest version JAR, selected winter 2017 and only included MAT1322 and could not generate any schedule, all schedules said that they do not have any conflict free spots, same applied if I include ITI1121 (Both offered right now with multiple none-conflicting times). Has the software been updated to interact with the new course system since rabaska no longer is used?

**Comment by davidschlachter** [comment]
Hmm.. this is affecting some courses but not others (e.g. BIO1140 or CHG1125 work fine).

The schedule generator does use data from the new system and auto-updates about once a week. However, parsing data from the new system has been [a work in progress](https://github.com/morinted/schedule-generator/issues/14) and it's messier than the output from the old system. I'll check this out and figure out what's happening. (Some sort of automated testing would be great to know what portion of courses are failing to schedule 😃 )

**Comment by davidschlachter** [comment]
While parsing schedules the Server was failing on some course, and then failing to read subsequent courses (hence why BIO and CHG courses could schedule, but not those later in the alphabet like ITI or MAT courses). I made some changes to the parser to increase robustness (bb93ffc908fe9c974cdd5b51aca71aa8ef24e282), and now it looks like everything is working. Thank you for your bug report!
