### ISSUE TITLE
Not all activities being listed for courses

### ISSUE THREAD

**Issue by KingFelidae** [morinted/schedule-generator#16]
Can the program be updated for use with the new semesters?

**Comment by davidschlachter** [comment]
It [automatically updates timetables](https://schlachter.ca/schedgen/archive/) every few days. I've just started a manual update to check that there aren't any errors with the new semesters. I'll post here if there are any issues / if it goes fine.

**Comment by KingFelidae** [comment]
I just used it a minute ago and they are now there. Great work!

**Comment by davidschlachter** [comment]
Oops! The activity parser was skipping every other line — I've fixed this in 01eadca27837eff6e939e9ae40b3016b5db54a40 and it should work fine now.

(Also, timetables are automatically updated every four or five days, so they should stay up-to-date)
