### ISSUE TITLE
Schedules not generating

### ISSUE THREAD

**Issue by KingFelidae** [morinted/schedule-generator#17]
Hey sorry to post another issue. Since your update on the course activities parsing error, the  program does not seem to generate schedules. When I click "Generate Schedules" a blue loading bar starts to fill, gets to what looks like 99% (visually) and then hangs indefinitely.

**Comment by davidschlachter** [comment]
No, thank you for reporting this! It looks like it was just server weirdness (I hadn't restarted the server when I updated the executable). I've just restarted it and generated some schedules again. Let me know if you're having any more trouble, and please reopen the issue if it's not working for you!
