### ISSUE TITLE
Missing Course

### ISSUE THREAD

**Issue by sclel016** [morinted/schedule-generator#18]
Just came across this tool, I love it. I was trying it out on my course sequence and the project course ELG4912 is in not in the Fall 2017 semester list. See [Link](https://web30.uottawa.ca/v3/SITS/timetable/Course.aspx?id=011437&term=2179&session=FS) for ELG4912.

Thanks!

**Comment by davidschlachter** [comment]
Oops! This was related to #16 — I've fixed it in 739833e. Every other section for a course was being skipped, but it's fixed now and ELG4912 appears for both semesters.
