### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by butasinghji** [morinted/schedule-generator#20]
Hello

First off this is an amazing app! Thank you!!

Sorry to open an issue, No information is showing in the scheduler I presume because it is not connecting to the server. I am running Windows 10 and have the latest version  1.1.1

Can you please advise?

Thanks

**Comment by davidschlachter** [comment]
The server must have rebooted while updating schedules, leaving the job half done. I've updated them and now everything's back to normal. Thanks for the report!

**Comment by butasinghji** [comment]
David

Much appreciated, it now works!!

Thank you very much!
