### ISSUE TITLE
Some courses not loading

### ISSUE THREAD

**Issue by marcturpin91** [morinted/schedule-generator#26]
Some of the courses are not being loaded for Winter 2019. For example, PHI, PHY, SEG courses are not being populated when entering those course codes. They do load however for Fall 2018. 

If I have time, I will look into it myself and update my findings here.

**Comment by davidschlachter** [comment]
I updated the courses again — are you still seing this issue? I had been experimenting with the Safari webdriver earlier and it sometimes tried to hit the 'Next' button before each page in the courses list was fully loaded, so it may have failed to get the full courses list. This would have causes course codes later in the alphabet not to have been retrieved. Just re-ran getCourses.py on the Ubuntu VM I usually use and I'm seeing the courses you describe.

![capture d ecran 2018-05-21 a 10 04 40](https://user-images.githubusercontent.com/8271268/40311629-676a046e-5cde-11e8-9e25-676581d13b93.png)

**Comment by marcturpin91** [comment]
Yep that seemed to have fixed it. Cheers :)

**Comment by alcauda** [comment]
The PHY 1000 courses are not showing up for me either. (I'm specifically looking for course PHY1331). Would you mind trying to update the courses again to see if this works?
