### ISSUE TITLE
PHI1101 Fall - Merging multiple sections together

### ISSUE THREAD

**Issue by OttUDad** [morinted/schedule-generator#28]
When generating the schedule for fall using PHI1101 sections H and C seem to be merged with another section causing 4 "90 minute" lecture slots for 1 class.  It might be related to H and C having extra lines in the schedule i.e. "PHI1101 HJ00
(September 05 - December 05)
CA Hawkesbury
Video-conference course"

**Comment by davidschlachter** [comment]
Yeah, the problem was that `getTimetables.py` was expecting the section id to be only one letter, but here we have two. Fixed this in 1dac0f63a08acd5f19ee60df89f8859feba39ce9. Thanks for reporting the issue!

**Comment by OttUDad** [comment]
Great!!  Thanks.
