### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by NGnius** [morinted/schedule-generator#31]
It seems that the server is down. Probably too popular with course selection opening up. The program will stay at the loading screen saying "Attempting to connect to server... Please wait (...)".

Also https://schlachter.ca/schedgen/ gives a 403 (Forbidden) error.

**Comment by davidschlachter** [comment]
Thanks for reporting — the `server.stat` file had become corrupted and was preventing the server from responding. Should be fine now, please re-open the issue if it doesn't work for you!
