### ISSUE TITLE
course-download scripts need to be updated

### ISSUE THREAD

**Issue by davidschlachter** [morinted/schedule-generator#32]
Looks like uOttawa has changed the timetables search tool again, course download scripts will need a re-write.

Link to new tool: https://uocampus.public.uottawa.ca/psp/csprpr9pub/EMPLOYEE/HRMS/c/UO_SR_AA_MODS.UO_PUB_CLSSRCH.GBL?languageCd=ENG

**Comment by MarcDAFrame** [comment]
any updates on this issue, I'm a regular user of this and wouldn't mind spending a few hours figuring it out.

**Comment by davidschlachter** [comment]
If you're interested, give it a go. I was planning to rewrite the scripts when I finish exams next week.

**Comment by MarcDAFrame** [comment]
ya after taking a closer look, I'd have to re write the whole getCourses.py and getTimetables.py without a reference to what the site used to look like / how it used to work

**Comment by davidschlachter** [comment]
Mostly fixed in e3d672bc3d54f298182da3958e121cc7851a2a9b and 9e7d0b208a02aa372f38bd425fb5ca7701a33abe, just uploaded the new schedules for 2019 Spring/Summer  :D
