### ISSUE TITLE
Can't connect to server :(

### ISSUE THREAD

**Issue by sajsaaj** [morinted/schedule-generator#40]
Unable to connect for a little while

**Comment by davidschlachter** [comment]
Server is online now and I don't see anything unusual in the logs yesterday — are you able to connect now? I'm seeing several recent connections in the logs and I'm able to connect too. Let me know if you're still having trouble, and thanks for reporting!

**Comment by sajsaaj** [comment]
It's working well now.
Thank you so much for responding so quickly!! This program saves me loads of time
I really appreciate it

**Comment by dimonoid** [comment]
Same issue, cannot connect to the server.

**Comment by davidschlachter** [comment]
I'm able to connect right now and don't see anything unusual in the server logs. Maybe try from a different network and/or a different machine? You need to be able to open a remote connection to schlachter.ca over TCP port 5555, maybe your network or firewall is blocking this. If you're running an old version of the schedule generator (before 2016) you may need to update.
