### ISSUE TITLE
Sometimes "Displaying schedule" counter shows negative numbers in the nominator

### ISSUE THREAD

**Issue by dimonoid** [morinted/schedule-generator#41]
I didn't understand exactly when it happens, but it is definitely a bug. Once reached negatives, one can still safely click next and last buttons to navigate, but the schedule is shown as empty.

**Comment by davidschlachter** [comment]
Thanks for the report! If you're able to reproduce the issue with a particular set of courses or steps, please add a comment so we can look into this further.

**Comment by davidschlachter** [comment]
Closing issue - unable to reproduce.
