### ISSUE TITLE
Error: Can't setup connection! Terminating Problem

### ISSUE THREAD

**Issue by BillyBolton** [morinted/schedule-generator#44]
<img width="1330" alt="Screen Shot 2019-12-05 at 11 37 25 PM" src="https://user-images.githubusercontent.com/50888798/70296357-5b376600-17b8-11ea-909e-fa9f1bacabdc.png">

**Comment by davidschlachter** [comment]
Thank you for reporting! The server has been down since Nov 29, the cause seems to be an update that killed the server, which then wasn't automatically restarted. Should be back online now!
