### ISSUE TITLE
Courses not updating, server hangs

### ISSUE THREAD

**Issue by Rofltropter** [morinted/schedule-generator#45]
Due to uOttawa's recent update of the course system, the endpoint to collect courses is now dead. Please PLEASE find the new url as this is the only way to schedule courses without blowing my brains out.

**Comment by davidschlachter** [comment]
Looks like courses haven't automatically updated [since Nov 13](https://schlachter.ca/schedgen/archive/). The server is also hanging more often, probably when trying to update courses that haven't successfully updated. For now, I'll disable automatic updates since it looks like they may be failing, and make sure the server is restarted more often to keep it online. I'll take a look at this issue over the holiday break.

**Comment by Rofltropter** [comment]
First off, you're a top tier developer for answering so quickly, my hat off to you Sir!

Would there be any collection of courses we could manually download and have the program parse instead? I know your README had specified a python script to bring the collection local, perhaps there is still a way about this? 

Is there a maintainer contact within uOttawa for this database? I can reach out to them or have once of the Dean's reach out to them on our behalf. 

Quite honestly, the "new" uOzone is brutally terrible. I wouldn't be surprised if many a student have come across your application as their last saving grace.

**Comment by Rofltropter** [comment]
IE Can I load in the Nov 13th material and use that?

**Comment by davidschlachter** [comment]
The server is currently using the Nov 13th data. It looks like it just needs to be restarted more often on my end at the moment to stay online.

**Comment by Rofltropter** [comment]
Thanks mate. I've just booked my courses successfully because of you. I'll keep this issue open so you can refer back to it over the break. Feel free to reach out if you need any assistance.

Cheers,

Daniel

**Comment by BillyBolton** [comment]
I'm not sure if this is the same issue, but it looks like the program stalls only when I add MAT 1348 into the program.

<img width="1448" alt="Screen Shot 2019-12-10 at 3 52 15 PM" src="https://user-images.githubusercontent.com/50888798/70568157-5b8f8280-1b65-11ea-9c4b-61052df306e4.png">

**Comment by davidschlachter** [comment]
HI @BillyBolton, this is a separate issue -- I've opened #46 to track it. Again, I'll take a look at this over the holidays. Thank you for reporting!

**Comment by davidschlachter** [comment]
Closing this issue since sometime around December 29th the schedule endpoint URL was reverted back to the old one and schedules have been automatically updating since then.
